server:
    port: 8080
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/workovertime?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: newpwd
      driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      view:
        prefix: /html/
        suffix: .html
    servlet:
      multipart:
        max-request-size: 10MB
        max-file-size: 10MB
    resources:
      static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","classpath:/templates/"]
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.six.group.user.entity
    configuration:
      map-underscore-to-camel-case: true
logging:
    level:
      com.six.group: debug
      org:
        springframework: debug
        mybatis: debug
        apache:
          ibatis: debug